# Generated by Django 4.2.25 on 2025-10-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpeexperience',
            name='title',
            field=models.CharField(default='Untitled Experience', max_length=200),
        ),
    ]
